[build]
  command = "npm run build"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Cache-Control = "no-store"
